name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.9]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Load data
        run: python NLP-MDF/data.py
      - name: Train model
        run: |
          python NLP-MDF/model.py
          python NLP-MDF/train.py
      - name: Predict Nationality
        run: python NLP-MDF/predict.py Gleeson
