name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.9]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Install PyTorch
        run: python3 -m pip install torch torchvision torchaudio
      - name: Load data
        run: python3 data.py
      - name: Train model
        run: python3 train.py
      - name: Predict Nationality
        run: python3 predict.py Gleeson
